name: Compila y Genera PDF

on:
  push:

jobs:
  compila:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener copia local del repositorio
        uses: actions/checkout@v4.2.2

      - name: Configurar .NET en el runner
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: '9.0.x'

      - name: Instalar dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

  crear-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener copia del repositorio
        uses: actions/checkout@v3

      - name: Convertir Markdown a PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: false

      - name: Subir artefacto generado
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
